# -*- coding: utf-8 -*-
"""Checkpoint 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mVLynkrRKgIyN-fEYU4QqN4lQ4KizmqR

# **Video Game Sale**

# **Import Library**
"""

import pandas as pd

"""# **Memuat Dataset**"""

file = "/vgsales.csv"
df = pd.read_csv(file)
df

from google.colab import drive
drive.mount('/content/drive')

"""# **Bussnies Understanding**

## **Bussnies Objective**

**Deskripsi Data**
Data ini merupakan data penjualan video game di seluruh dunia yang berhasil terjual lebih dari 100.000 kopi. Di dalamnya terdapat informasi mulai dari Genre (jenis permainan), *Platform*(konsol yang digunakan), Tahun Rilis, hingga angka penjualan spesifik di beberapa *Region* seperti Amerika Utara, Eropa, dan Jepang.

Industri video game adalah industri yang bernilai miliaran dolar, namun persaingannya sangat ketat. Banyak pengembang game (*developer*) dan penerbit (*publisher*) mengalami kerugian karena merilis game yang tidak sesuai dengan selera pasar. Masalah utamanya adalah sulitnya menentukan kombinasi *Genre*, *Platform*, dan target pasar (*Region*) yang tepat untuk memaksimalkan keuntungan.

## **Asses Situation**

**Kondisi Dataset:**
Saya menggunakan dataset `vgsales.csv` yang bersumber dari Kaggle.
* Dataset ini memiliki lebih dari 16.500 data penjualan.
* Terdiri dari kolom penting seperti `Rank`, `Name`, `Platform`, `Year`, `Genre`, `Publisher`, dan data penjualan per wilayah (`NA_Sales`, `EU_Sales`, `JP_Sales`, `Other_Sales`).

**Tantangan & Risiko:**

* Terdapat beberapa data tahun dan penerbit yang kosong, sehingga perlu dibersihkan nanti.
* Data yang dominan mencakup game lama dari sekitar tahun 2016-2020. Sehingga game terbaru mungkin tidak terlalu terekspos.

## **Analytic Goals Projects Plan**

* Membuat grafik batang dan pie chart untuk melihat distribusi *Genre* terpopuler dan *Platform* dengan penjualan tertinggi.

* Mencari hubungan antara wilayah penjualan. misalnya, Apakah game yang laku di Jepang bisa laku di Amerika?

## **Project plan**

* Mengecek isi data dan seberapa banyak data tahun/penerbit yang kosong.
* Membersihkan data yang kosong agar siap diolah.
"""